/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BecomeApprovedRouteImport } from './routes/become-approved'
import { Route as CommunityRulesRouteImport } from './routes/community-rules'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedApplicationRouteImport } from './routes/_authenticated/application'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ContractorsIndexRouteImport } from './routes/contractors.index'
import { Route as ContractorsIdRouteImport } from './routes/contractors.$id'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminIdRouteImport } from './routes/_authenticated/admin.$id'
import { Route as AuthenticatedAdminRolesRouteImport } from './routes/_authenticated/admin.roles'
import { Route as AuthenticatedAdminApplicationsApplicationIdRouteImport } from './routes/_authenticated/admin.applications.$applicationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeApprovedRoute = BecomeApprovedRouteImport.update({
  id: '/become-approved',
  path: '/become-approved',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRulesRoute = CommunityRulesRouteImport.update({
  id: '/community-rules',
  path: '/community-rules',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplicationRoute =
  AuthenticatedApplicationRouteImport.update({
    id: '/application',
    path: '/application',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ContractorsIndexRoute = ContractorsIndexRouteImport.update({
  id: '/contractors/',
  path: '/contractors/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorsIdRoute = ContractorsIdRouteImport.update({
  id: '/contractors/$id',
  path: '/contractors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminIdRoute = AuthenticatedAdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRolesRoute = AuthenticatedAdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminApplicationsApplicationIdRoute =
  AuthenticatedAdminApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-approved': typeof BecomeApprovedRoute
  '/community-rules': typeof CommunityRulesRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/application': typeof AuthenticatedApplicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/contractors/$id': typeof ContractorsIdRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/applications/$applicationId': typeof AuthenticatedAdminApplicationsApplicationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/become-approved': typeof BecomeApprovedRoute
  '/community-rules': typeof CommunityRulesRoute
  '/application': typeof AuthenticatedApplicationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/contractors/$id': typeof ContractorsIdRoute
  '/contractors': typeof ContractorsIndexRoute
  '/admin/$id': typeof AuthenticatedAdminIdRoute
  '/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/applications/$applicationId': typeof AuthenticatedAdminApplicationsApplicationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/become-approved': typeof BecomeApprovedRoute
  '/community-rules': typeof CommunityRulesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/application': typeof AuthenticatedApplicationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/contractors/$id': typeof ContractorsIdRoute
  '/contractors/': typeof ContractorsIndexRoute
  '/_authenticated/admin/$id': typeof AuthenticatedAdminIdRoute
  '/_authenticated/admin/roles': typeof AuthenticatedAdminRolesRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/applications/$applicationId': typeof AuthenticatedAdminApplicationsApplicationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/become-approved'
    | '/community-rules'
    | '/admin'
    | '/application'
    | '/dashboard'
    | '/contractors/$id'
    | '/contractors/'
    | '/admin/$id'
    | '/admin/roles'
    | '/admin/'
    | '/admin/applications/$applicationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/become-approved'
    | '/community-rules'
    | '/application'
    | '/dashboard'
    | '/contractors/$id'
    | '/contractors'
    | '/admin/$id'
    | '/admin/roles'
    | '/admin'
    | '/admin/applications/$applicationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/become-approved'
    | '/community-rules'
    | '/_authenticated/admin'
    | '/_authenticated/application'
    | '/_authenticated/dashboard'
    | '/contractors/$id'
    | '/contractors/'
    | '/_authenticated/admin/$id'
    | '/_authenticated/admin/roles'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/applications/$applicationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BecomeApprovedRoute: typeof BecomeApprovedRoute
  CommunityRulesRoute: typeof CommunityRulesRoute
  ContractorsIdRoute: typeof ContractorsIdRoute
  ContractorsIndexRoute: typeof ContractorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-approved': {
      id: '/become-approved'
      path: '/become-approved'
      fullPath: '/become-approved'
      preLoaderRoute: typeof BecomeApprovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community-rules': {
      id: '/community-rules'
      path: '/community-rules'
      fullPath: '/community-rules'
      preLoaderRoute: typeof CommunityRulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/application': {
      id: '/_authenticated/application'
      path: '/application'
      fullPath: '/application'
      preLoaderRoute: typeof AuthenticatedApplicationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/contractors/': {
      id: '/contractors/'
      path: '/contractors'
      fullPath: '/contractors/'
      preLoaderRoute: typeof ContractorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractors/$id': {
      id: '/contractors/$id'
      path: '/contractors/$id'
      fullPath: '/contractors/$id'
      preLoaderRoute: typeof ContractorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/$id': {
      id: '/_authenticated/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AuthenticatedAdminIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/roles': {
      id: '/_authenticated/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AuthenticatedAdminRolesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/applications/$applicationId': {
      id: '/_authenticated/admin/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/admin/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedAdminApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIdRoute: typeof AuthenticatedAdminIdRoute
  AuthenticatedAdminRolesRoute: typeof AuthenticatedAdminRolesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminApplicationsApplicationIdRoute: typeof AuthenticatedAdminApplicationsApplicationIdRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIdRoute: AuthenticatedAdminIdRoute,
  AuthenticatedAdminRolesRoute: AuthenticatedAdminRolesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminApplicationsApplicationIdRoute:
    AuthenticatedAdminApplicationsApplicationIdRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedApplicationRoute: typeof AuthenticatedApplicationRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedApplicationRoute: AuthenticatedApplicationRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BecomeApprovedRoute: BecomeApprovedRoute,
  CommunityRulesRoute: CommunityRulesRoute,
  ContractorsIdRoute: ContractorsIdRoute,
  ContractorsIndexRoute: ContractorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
